#include "platform.hpp"
#include "core.hpp"
#include "intro.hpp"
#include <chrono>
#include <cstdio>
#include <memory>
using namespace scorch;
enum class Screen {Intro,Menu,Options,Tank,Name,Play,Help,ExitConfirm,ExitChoice,Round,Match,NewGame};
struct App {
 Assets assets; Image frame{640,480},field{640,480},before{640,480},tankBackground[2];
 Screen screen=Screen::Intro; Options options,editing; Game game; std::string names[2];
 int menu=0,option=0,setup=0,selection=0;bool quit=false,shooting=false,level=false;Shot shot{};Point previous{},impact{};int shotPhase=0,radius=0;double elapsed=0,shotClock=0;HWND window=nullptr;
 explicit App(std::filesystem::path root):assets{root,{}}{}
 void image(const std::string& n,int x=0,int y=0){blit(frame,assets.get(n),x,y);}
 void label(const std::string& s,int x,int y){text(frame,assets.get("font.png"),s,x,y);}
 std::string number(int n,int width){char b[32];snprintf(b,sizeof b,"%0*d",width,n);return b;}
 void mainMenu(){image("menu.png");const char* roll[]={"play.png","options.png","credits.png","exit.png"};image(roll[menu],333,88);int boxes[4][4]={{25,90,220,138},{25,182,220,232},{24,274,219,318},{23,360,218,402}};auto b=boxes[menu];rect(frame,b[0],b[1],b[2],b[3],0xffffffff);rect(frame,b[0]+1,b[1]+1,b[2]-1,b[3]-1,0x808080);}
 void modal(const std::string& n,bool mini=false){dim(frame);image(n,mini?120:80,mini?160:60);}
 void tankScreen(){mainMenu();modal(setup?"p2tankmenu.png":"p1tankmenu.png");int p[6][2]={{208,201},{350,198},{483,200},{206,332},{320,330},{487,342}};flood(frame,p[selection][0],p[selection][1],0xffff00);}
 void stats(){label(names[0],75,414);label(names[1],499,414);label(number(displayedScore(game.players[0].points.score),5),81,434);label(number(displayedScore(game.players[1].points.score),5),505,434);auto& p=game.players[game.turn-1];label(number(p.power,3),300,422);label(number(p.angle,3),300,444);for(int i=0;i<2;i++){int x=i?505:82;for(int j=0;j<5;j++){rect(frame,x+j*25,454,x+(j+1)*25,469,0x7700);if(j<(game.players[i].radius-15)/5)rect(frame,x+j*25+1,455,x+(j+1)*25-1,468,0xf0,true);}rect(frame,x-1,453,x+126,470,0xf0);}flood(frame,189,425,game.turn==1?0xffff00:0x010101);flood(frame,613,425,game.turn==2?0xffff00:0x010101);if(options.wind){label("00",373,430);flood(frame,398,461,0xffff00);}}
 void tank(int i){auto p=tankCoords[game.land][i];auto& t=game.players[i];blit(field,tankBackground[i],p.x,p.y);blit(field,assets.get("tank"+std::to_string(t.model)+".png"),p.x,p.y,0,t.frame*60,60,60,true);}
 void startRound(){field=assets.get("main.png");rect(field,0,12,639,12,0x808080);rect(field,0,13,639,13,0x404040);rect(field,0,410,639,479,0xffffff);rect(field,0,410,215,479,0xffffff);rect(field,1,411,214,478,0x808080);rect(field,420,410,639,479,0xffffff);rect(field,421,411,638,478,0x808080);rect(field,216,411,419,478,0x808080);rect(field,0,14,639,410,options.sky,true);blit(field,assets.get("land.png"),0,14,0,game.land*397,640,397,true);for(int i=0;i<2;i++){auto p=tankCoords[game.land][i];tankBackground[i]=Image(60,60);blit(tankBackground[i],field,0,0,p.x,p.y,60,60);tank(i);}screen=Screen::Play;shooting=false;if(options.wind&&options.sound)firingSound();}
 void newMatch(){int a=game.players[0].model,b=game.players[1].model;game=Game(options);game.players[0].model=a;game.players[1].model=b;startRound();}
 void render(){
 if(screen==Screen::Intro){frame=Image(640,480);for(auto f:introFrames(elapsed)){if(f.asset==introFadeCommand){for(auto& p:frame.pixels)p=introFadePixel(p);}else image(f.asset);}return;}
 if(screen==Screen::Menu){mainMenu();return;}
 if(screen==Screen::Tank||screen==Screen::Name){tankScreen();if(screen==Screen::Name){modal("namemenu.png",true);label(names[setup],237,264);}return;}
 if(screen==Screen::Options){mainMenu();modal("optionsmenu.png");image("rightarrow.png",94,135+option*50);if(editing.wind)flood(frame,370,158,0xffff00);if(editing.sound)flood(frame,370,207,0xffff00);int rx[]={376,414,449,485,521},ry[]={243,242,248,242,249};flood(frame,rx[(editing.rounds-1)/2],ry[(editing.rounds-1)/2],0xffff00);image("uparrow.png",361+(editing.color-1)*35,320);return;}
 if(screen==Screen::Help&&menu==2){mainMenu();modal("credit.png");return;}
 frame=field;stats();
 if(screen==Screen::Help)modal("helpmenu.png");
 if(screen==Screen::ExitConfirm)modal("exitmain.png",true);
 if(screen==Screen::ExitChoice)modal("exittomain.png",true);
 if(screen==Screen::Round){modal("endofround.png");label(std::to_string(options.rounds-game.roundsRemaining),313,154);label(names[game.winner-1],353,220);label(number(displayedScore(roundScore(game.players[game.winner-1].turns)),5),353,264);if(level)image("levelup.png",206,333);}
 if(screen==Screen::Match||screen==Screen::NewGame){modal("endofgame.png");for(int i=0;i<2;i++){int x=i?388:125;label(names[i],x,202);label(number(displayedScore(game.players[i].points.score),5),x,234);}label(std::to_string(game.players[0].wins)+":"+std::to_string(game.players[1].wins),298,276);image("trophy.png",game.matchWinner()==1?162:418,329);if(screen==Screen::NewGame)modal("newgame.png",true);}
 }
 void beginShot(){auto& p=game.players[game.turn-1];game.fired();previous=shotOrigin(game.land,game.turn,p.model,p.frame);shot=launch(previous,p.power,p.angle);before=field;shooting=true;shotPhase=0;shotClock=0;if(options.sound)firingSound();}
 void nextTurn(){shooting=false;game.switchTurn();if(options.wind&&options.sound)firingSound();}
 void update(double dt){elapsed+=dt;if(screen==Screen::Intro&&elapsed>=introDuration)screen=Screen::Menu;if(!shooting||screen!=Screen::Play)return;shotClock+=dt;if(shotPhase==0){if(shotClock<0.0549254)return;shotClock=0;auto p=sample(shot,0);auto r=traceBullet(previous,p,options.sky,[&](Point q){return field.get(q.x,q.y);},[&](Point q){field.put(q.x,q.y,0xffffff);});previous=p;if(r.kind==TraceKind::hit){impact=r.point;shotPhase=1;radius=0;}else if(r.kind==TraceKind::outOfBounds||shot.t>2048){shotPhase=3;}}
 else if(shotPhase==1){if(shotClock<0.275)return;int max=game.players[game.turn-1].radius;circle(field,impact.x,impact.y,radius,0xffa00000,true);if(++radius>=max){shotPhase=2;shotClock=0;}}
 else if(shotPhase==2&&shotClock>=0.55){field=before;int max=game.players[game.turn-1].radius;for(int r=max;r>0;r--)circle(field,impact.x,impact.y,r,options.sky,options.sky!=0);int dead=hitPlayer(impact,game.land,game.players[0].model,game.players[1].model,max);if(dead){if(options.sound)impactSound();level=game.finishRound(dead);shotPhase=4;radius=0;shotClock=0;}else nextTurn();}
 else if(shotPhase==3&&shotClock>=1.0985){field=before;nextTurn();}
 else if(shotPhase==4){for(int i=0;i<12&&radius<600;i++)circle(field,impact.x,impact.y,radius++,0xffa00000,true);if(radius>=600){shooting=false;screen=Screen::Round;if(level&&options.sound)playNotes({{3100,2},{2600,2},{2850,2},{2200,2},{3100,2},{2600,2},{2850,2},{2200,2}});}}}
 void key(int k){if(screen==Screen::Intro){screen=Screen::Menu;return;}if(screen==Screen::Menu){if(k==VK_UP)menu=(menu+3)%4;if(k==VK_DOWN)menu=(menu+1)%4;if(k==VK_RETURN){if(menu==0){setup=selection=0;names[0]=names[1]="";screen=Screen::Tank;}if(menu==1){editing=options;option=0;screen=Screen::Options;}if(menu==2)screen=Screen::Help;if(menu==3)quit=true;}return;}
 if(screen==Screen::Tank){if(k==VK_UP||k==VK_DOWN)selection=(selection+3)%6;if(k==VK_LEFT)selection=selection/3*3+(selection%3+2)%3;if(k==VK_RIGHT)selection=selection/3*3+(selection%3+1)%3;if(k==VK_RETURN){game.players[setup].model=selection+1;screen=Screen::Name;}return;}
 if(screen==Screen::Name){if(k==VK_BACK&&!names[setup].empty())names[setup].pop_back();if(k==VK_RETURN){if(setup==0){setup=1;selection=0;screen=Screen::Tank;}else newMatch();}return;}
 if(screen==Screen::Options){if(k=='Q'||k==VK_ESCAPE){screen=Screen::Menu;return;}if(k==VK_UP)option=std::max(0,option-1);if(k==VK_DOWN)option=std::min(4,option+1);if(k==VK_LEFT||k==VK_RIGHT){int d=k==VK_RIGHT?1:-1;if(option==0)editing.wind=d>0;if(option==1)editing.sound=d>0;if(option==2)editing.rounds=std::clamp(editing.rounds+2*d,1,9);if(option==3)editing.color=std::clamp(editing.color+d,1,5);}if(k==VK_RETURN&&option==4){uint32_t colors[]={0,0x4040,0xd24b00,0x408080,0x234567};editing.sky=colors[editing.color-1];options=editing;screen=Screen::Menu;}return;}
 if(screen==Screen::Help){if(k==VK_RETURN||k==VK_ESCAPE)screen=menu==2?Screen::Menu:Screen::Play;return;}
 if(screen==Screen::ExitConfirm){if(k=='Y')screen=Screen::ExitChoice;if(k=='N'||k==VK_ESCAPE)screen=Screen::Play;return;}
 if(screen==Screen::ExitChoice){if(k=='M'){menu=0;screen=Screen::Menu;}if(k=='Q')quit=true;return;}
 if(screen==Screen::Round&&k==VK_RETURN){if(game.roundsRemaining==0){screen=Screen::Match;if(options.sound)battleHymn();}else{game.nextRound();startRound();}return;}
 if(screen==Screen::Match&&k==VK_RETURN){screen=Screen::NewGame;return;}
 if(screen==Screen::NewGame){if(k=='Y')newMatch();if(k=='N')screen=Screen::ExitChoice;return;}
 if(screen==Screen::Play&&!shooting){auto& p=game.players[game.turn-1];if(k==VK_UP)p.angle=std::min(180,p.angle+1);if(k==VK_DOWN)p.angle=std::max(0,p.angle-1);if(k==VK_LEFT)p.power=std::max(0,p.power-1);if(k==VK_RIGHT)p.power=std::min(100,p.power+1);if(k==VK_UP||k==VK_DOWN){int f=updateTankFrame(p.frame,p.angle);if(f!=p.frame){p.frame=f;tank(game.turn-1);}}if(k==VK_RETURN)beginShot();if(k==VK_F1){menu=0;screen=Screen::Help;}if(k=='Q'||k==VK_ESCAPE)screen=Screen::ExitConfirm;}}
 void character(wchar_t c){if(screen==Screen::Name&&names[setup].size()<10&&(c==' '||(c>='a'&&c<='z')))names[setup]+=char(c);}
};
std::unique_ptr<App> app;
LRESULT CALLBACK windowProc(HWND w,UINT m,WPARAM a,LPARAM b){switch(m){case WM_KEYDOWN:app->key(int(a));InvalidateRect(w,nullptr,FALSE);return 0;case WM_CHAR:app->character(wchar_t(a));return 0;case WM_TIMER:{static auto last=std::chrono::steady_clock::now();auto now=std::chrono::steady_clock::now();app->update(std::chrono::duration<double>(now-last).count());last=now;if(app->quit)DestroyWindow(w);else InvalidateRect(w,nullptr,FALSE);return 0;}case WM_ERASEBKGND:return 1;case WM_PAINT:{PAINTSTRUCT p;HDC dc=BeginPaint(w,&p);app->render();RECT r;GetClientRect(w,&r);FillRect(dc,&r,(HBRUSH)GetStockObject(BLACK_BRUSH));int W=r.right,H=r.bottom;double scale=std::min(W/640.0,H/480.0);int dw=int(640*scale),dh=int(480*scale);BITMAPINFO bi{};bi.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);bi.bmiHeader.biWidth=640;bi.bmiHeader.biHeight=-480;bi.bmiHeader.biPlanes=1;bi.bmiHeader.biBitCount=32;bi.bmiHeader.biCompression=BI_RGB;SetStretchBltMode(dc,COLORONCOLOR);StretchDIBits(dc,(W-dw)/2,(H-dh)/2,dw,dh,0,0,640,480,app->frame.pixels.data(),&bi,DIB_RGB_COLORS,SRCCOPY);EndPaint(w,&p);return 0;}case WM_DESTROY:PostQuitMessage(0);return 0;}return DefWindowProc(w,m,a,b);}
int WINAPI wWinMain(HINSTANCE h,HINSTANCE,PWSTR cmd,int show){CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{wchar_t path[32768];GetModuleFileNameW(nullptr,path,32768);auto root=std::filesystem::path(path).parent_path()/L"picts";app=std::make_unique<App>(root);for(auto& e:std::filesystem::recursive_directory_iterator(root))if(e.path().extension()==L".png")app->assets.get(std::filesystem::relative(e.path(),root).generic_string());
 if(std::wstring(cmd).find(L"--smoke-test")!=std::wstring::npos){app->screen=Screen::Menu;app->render();saveBMP(app->frame,"smoke-menu.bmp");app->names[0]="player one";app->names[1]="player two";app->newMatch();app->render();saveBMP(app->frame,"smoke-game.bmp");app->game.players[0].power=65;app->game.players[0].angle=44;app->game.players[0].frame=2;app->tank(0);app->beginShot();for(int i=0;i<2000&&app->shooting;i++)app->update(.016);if(app->shooting)return 3;app->render();saveBMP(app->frame,"smoke-shot.bmp");std::ofstream("smoke-result.txt")<<"Native WIC decoded "<<app->assets.images.size()<<" PNGs; menus, initial round, shot termination and BMP rendering passed.\n";return 0;}
 SetProcessDPIAware();WNDCLASSW wc{};wc.lpfnWndProc=windowProc;wc.hInstance=h;wc.lpszClassName=L"ScorchedEverittNative";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);RECT r{0,0,960,720};AdjustWindowRect(&r,WS_OVERLAPPEDWINDOW,FALSE);HWND w=CreateWindowW(wc.lpszClassName,L"Scorched Everitt — Native Windows",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,r.right-r.left,r.bottom-r.top,nullptr,nullptr,h,nullptr);app->window=w;ShowWindow(w,show);SetTimer(w,1,16,nullptr);MSG msg;while(GetMessage(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessage(&msg);}app.reset();CoUninitialize();return 0;}catch(const std::exception& e){MessageBoxA(nullptr,e.what(),"Scorched Everitt",MB_ICONERROR);return 1;}}
